language: python
python:
  - 2.7
# whitelist
branches:
  only:
    - master
    - dev
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  coverage run --source=psiturk setup.py test
after_success:
  coveralls
