language: python
python:
  - 2.7
branches:
  only:
    - master
    - dev
notifications:
  email: 
    - authors@psiturk.org
  on_success: change
  on_failure: always
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - python setup.py install
  - psiturk-setup-example
  - coverage run --source=psiturk setup.py test
after_success:
  coveralls
