language: python
before_install:
- sudo rm -f /etc/boto.cfg
env:
- PYTHON=python
- PIP=pip
matrix:
    include:
        - name: "Python 2.7 on macOS"
          os: osx
          osx_image: xcode11
          language: shell
        - name: "Python 3.7 on macOS"
          os: osx
          osx_image: xcode11
          language: shell
          env: PIP=pip3 PYTHON=python3
        - name: "Python 2.7 on linux"
          python: 2.7
        - name: "Python 3.6 on linux"
          python: 3.6
          env: PIP=pip3
        - name: "Python 3.7 on linux"
          python: 3.7
          env: PIP=pip3
install:
- $PIP install -r requirements.txt
- $PIP install coverage
- $PIP install coveralls
script:
- $PYTHON setup.py test
- coverage run --source=psiturk setup.py test
git:
    quiet: true
after_success: coveralls
deploy:
    # test pypi pip deployment
#  - provider: pypi
#    server: https://test.pypi.org/legacy/
#    user: nyuccl
#    password:
#      secure: h8nh6ooykI7eniajVkE/MYxZgyZoxcKRODhFWUwjlSHRmUV2tW/n2i/4MYJvMQXqiBgO64nOPmNhNH0mhYY+GbwyinAThRn3xhPIUfO8tV+edpzlzSwnGT+xSRINoUaGZfrs5UqCPVS7Ff5EB4SYRfrYBoV2VA5sx1XxoKKPkU4=
#    on:
#      tags: false
#      branch: master
         
    # production pypi
  - provider: pypi
    user: nyuccl
    password:
      secure: h8nh6ooykI7eniajVkE/MYxZgyZoxcKRODhFWUwjlSHRmUV2tW/n2i/4MYJvMQXqiBgO64nOPmNhNH0mhYY+GbwyinAThRn3xhPIUfO8tV+edpzlzSwnGT+xSRINoUaGZfrs5UqCPVS7Ff5EB4SYRfrYBoV2VA5sx1XxoKKPkU4=
    skip_existing: true
    on:
      tags: true
      branch: python2
