language: python
python:
  - 2.7
# whitelist
branches:
  only:
    - master
    - dev
notifications:
  email:
    recipients:
      - authors@psiturk.org
    on_success: change
    on_failure: always
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  coverage run --source=psiturk setup.py test
after_success:
  coveralls
